# Site settings
title: "Z0rd0n's Explorations"
email: xpl0r.scott@gmail.com
description: "A gateway into Andrew's destiny"
baseurl: ""
url: "http://z0rd0n.github.io"
twitter_username: Z0rd0nVoyage
github_username: z0rd0n
facebook_username: TrikBomb
# Build settings
markdown: kramdown
permalink: pretty
exclude: ["node_modules"]
