# Site settings
title: "Andrew's Big Ride Adventure- $4.50 a pint"
email: tmbrwlf103@gmail.com
description: "A gateway into Andrew's destiny"
baseurl: ""
url: "http://z0rd0n.github.io"
twitter_username: Z0rd0nVoyage
github_username: z0rd0n
facebook_username: TrikBomb
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
